id: I27479095
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:29:10.010488
last_modified: 2023-01-04 11:29:10.010495
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  8A11:
    title: 'Bodhicaryāvatāra: Teachings and Overview'
    base_file: 8A11.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
